### PR TITLE
Improve module name

### PR DESCRIPTION
**Pull request by leoheck**
Hi, I would like to improve the context menu name of this module. Is it possible to make PRs here? I am doing it on the master branch because the change is just a simple string.

### CODE REVIEW

**Comment by easyw** [comment]
I would not remove the 'WB' suffix because StepUp can be also a macro...

**Comment by leoheck** [comment]
I see this name on the WB drop-down list on Freecad. There are only workbenches there.
Are there other places where that string appears?

Why it should be different for macro and WB?

**Comment by easyw** [comment]
> Why it should be different for macro and WB?

The macro is a standalone file that can be used even without installing the WB... You are right that the drop-down list is referring to WBs, but I prefer to keep this exposed.

**Comment by leoheck** [comment]
Alright, added it back. But it still does not make sense to me. So, why not to add "Macro" for the macro and remove Wb from here?

**Comment by easyw** [comment]
> But it still does not make sense to me. So, why not to add "Macro" for the macro and remove Wb from here?

The macro came before the WB and its name cannot be changed without generating issues to users.

**Pull request merged**
