### PR TITLE
Multiple 3D model paths

### PR DESCRIPTION
**Pull request by CaptKrisp**
Add ability to search multiple paths for 3D models.
Multiple paths can be configured in 'main 3D folder location' and 'secondary 3D folder loc' fields.
These 2 fields can be comma or carriage return separated lists of paths.
Currently multiple paths in these fields must be manually entered and not by using the '...' button.

### CODE REVIEW

**Comment by easyw** [comment]
@CaptKrisp 
thanks for this PR... I'm going to review it and will update here

**Comment by CaptKrisp** [comment]
Hi @easyw,
Just curious if you have had opportunity to review my PR and decided for/against incorporating in your code.
Cheers,
Cap

**Comment by easyw** [comment]
@CaptKrisp 
sorry for being late on reviewing your PR.
The PR is improving the tool with a nice feature.
I just tried to incorporate it but I would need to check if the new function 'findModelPath' is called in all the needed instances.
The searching part of the code has been written almost since my first release of StepUp and it is not easy to modify it without risking to break some features.
Let me give an other try to review it.

**Comment by CaptKrisp** [comment]
Hi @easyw ,

Thanks for the reply.
I completely understand how difficult it can be to review code changes created by another person ... especially when it's been a long time since working in the affected section of code.

I use your script once or twice a year when designing 3D printed cases for PCBs that I design in my projects.  The biggest drawback for me in using it is (was) that most of my component models are in several locations and having only 2 model paths available meant most of my models needed to be loaded manually (a slight pain for the usual 1-2 dozen I often had) and then they aren't placed in the FreeCAD PCB container your script creates.

So I decided to look at your code and expand the number of paths the user could provide (either comma or carriage-return separated list).
After adding that functionality, I thought it would be even better if the script could import the model paths that KiCad uses (with the new function 'loadKiCadPrefsPath').  With this addition, if the user has all model paths specified in KiCad, there is essentially no need to even have the 2 model path variables ('models3D_prefix' and 'models3D_prefix2').  But I also believe it is an advantage to allow users to specify additional paths so keeping one or both 'models3D_prefix' variables, either with or without the comma-separated functionality I added, is preferred. :)

These code changes work perfectly for me... on a Mac.  But other platforms might have problems which I haven't test for.
Let me know if I can assist with any aspect of testing the proposed code changes.  I can create VMs for any of the Unix flavors or Windows 7 (don't have or want Windows 10) for testing in those environments, if you'd like me to.

BTW, great work on this project!

Cheers,
Cap

**Pull request closed without merging**
